/**
 * Interfaz para ingresar  una nueva sala
 * 
 * @author kevin Robles, Raquel Rojas
 * @version 1.0
 */
package vista;

public class RegistrarSala extends javax.swing.JFrame {
  
  /**
   * Metodo Constructor
   */
  public RegistrarSala() {
    initComponents();
  }
  
  /**
   * Metodo para validar el acceso de los datos
   * 
   * @return true si los datos son correctos, false de lo contrario
   */
  public boolean logInDatosCorrectos(){
    if (0==0){
      return false;
    }
    return true;
  }
  
  /**
   * Metodo para abrir la ventana anterior
   * 
   * @param ventanaAnterior interfaz a abrir
   */
  public void abrirVentanaAnterior(RegistrarSala ventanaAnterior){
    ventanaAnterior.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
  */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
